[package]
name = "cpm"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
config = "0.14.0"
serde = "1.0.197"
spdlog-rs = "0.3.13"
